rcv:
	g++ -std=c++11 -I ./Eigen/ test_rcv_10.cpp -o test
mnist:
	g++ -std=c++11 -I ./Eigen/ test_mnist.cpp -o test
news:
	g++ -std=c++11 -I ./Eigen/ test_news_100.cpp -o test
duke:
	g++ -std=c++11 -I ./Eigen/ test_duke.cpp -o test
ijcnn:
	g++ -std=c++11 -I ./Eigen/ test_ijcnn.cpp -o test
rna:
	g++ -std=c++11 -I ./Eigen/ test_rna.cpp -o test
gen:
	g++ -std=c++11 -I ./Eigen/ test_gen.cpp -o test
